// src/components/Grid.svelte
<script lang="ts">
    import { beforeUpdate } from 'svelte';
    import type { GridState } from "../modules/GridState";
    import { CrosswordStateStore } from "../modules/CrosswordStateStore";

    export let state:GridState;

    $: gridSizeInput = state.size;
    let hideLetters = false;
    let currentCellRow: number = null;
    let currentCellColumn: number = null;
    let cells: HTMLTableCellElement[][] = [];

    // Ensure that however the state gets updated we keep cells the correct size
	beforeUpdate(() => {
		if (gridSizeInput !== cells.length) {
            initialiseCells();
        }
	});

    function initialiseCells() {
        for (let i = 0; i < state.size; i++) {
            cells.push([])
        }
    }

    function cellFocusHandler(rowIndex: number, columnIndex: number) {
        currentCellRow = rowIndex;
        currentCellColumn = columnIndex;
    }

    function cellKeyDownHandler(rowIndex: number, columnIndex: number, event: KeyboardEvent) {
        // Don't handle Ctrl or Option key combinations
        if (!!event.metaKey || !!event.ctrlKey) {
            return;
        }
        event.preventDefault();
        switch (event.key) {
            case " ":
                CrosswordStateStore.toggleCell(rowIndex, columnIndex);
                break;
            case "Backspace":
            case "Delete":
                CrosswordStateStore.setCellLetter(rowIndex, columnIndex, "");
                break;
            case "ArrowUp":
                currentCellRow = Math.max(0, currentCellRow - 1);
                break;
            case "ArrowDown":
                currentCellRow = Math.min(state.size - 1, currentCellRow + 1);
                break;
            case "ArrowLeft":
                currentCellColumn = Math.max(0, currentCellColumn - 1);
                break;
            case "ArrowRight":
                currentCellColumn = Math.min(state.size - 1, currentCellColumn + 1);
                break;
            default:
                if (event.key.match(/^[a-z]$/i)) {
                    CrosswordStateStore.setCellLetter(rowIndex, columnIndex, event.key.toUpperCase());
                }
        }
        cells[currentCellRow][currentCellColumn].focus();
    }

    function sizeChangeHandler() {
        CrosswordStateStore.sizeGrid(gridSizeInput);
        currentCellRow = Math.min(currentCellRow, gridSizeInput - 1);
        currentCellColumn = Math.min(currentCellColumn, gridSizeInput - 1);
    }
</script>

<div>
    <p>
        <span class="grid-setting">
            Size: <select bind:value={gridSizeInput} on:change={sizeChangeHandler}>
                <option value={1}>1</option>
                <option value={2}>2</option>
                <option value={3}>3</option>
                <option value={4}>4</option>
                <option value={5}>5</option>
                <option value={6}>6</option>
                <option value={7}>7</option>
                <option value={8}>8</option>
                <option value={9}>9</option>
                <option value={10}>10</option>
                <option value={11}>11</option>
                <option value={12}>12</option>
                <option value={13}>13</option>
                <option value={14}>14</option>
                <option value={15}>15</option>
            </select>
        </span>
        <span class="grid-setting">
            Hide answers: <input type="checkbox" bind:checked={hideLetters} />
        </span>
    </p>
    <table class="grid">
        <tbody>
            {#each state.cells as row, rowIndex}
                <tr>
                    {#each row as cell, columnIndex}
                        <td tabindex="0"
                            class="cell {cell.isWhite ? "white" : "black"}"
                            on:focus={() => cellFocusHandler(rowIndex, columnIndex)}
                            on:keydown={(ev) => cellKeyDownHandler(rowIndex, columnIndex, ev)}
                            bind:this={cells[rowIndex][columnIndex]}>
                            {#if cell.isWhite}
                                <div class="cell-layout">
                                    <div class="cell-number" >
                                        {cell.cellNumber ?? ""}
                                    </div>
                                    {#if !hideLetters}
                                        <div class="cell-letter">
                                            {cell.answerLetter}
                                        </div>
                                    {/if}
                                </div>
                            {/if}
                        </td>
                    {/each}
                </tr>
            {/each}
        </tbody>
    </table>
</div>

<style lang="scss">
    .grid-setting {
        margin-right: 1.5em;
    }
    .grid {
        border-collapse: collapse;
    }
    .cell {
        padding: 0;
        height: 50px;
        width: 50px;
        border: solid 2px black;
    }
    .cell-layout {
        display: grid;
        grid-template-columns: 14px 34px;
        grid-template-rows: 14px 34px;
    }
    .cell-number {
        font-size: 11px;
        grid-row: 1 / 2;
        grid-column: 1 / 2;
        z-index: 1;
    }
    .cell-letter {
        text-align: center;
        line-height: 48px;
        grid-row: 1 / 3;
        grid-column: 1 / 3;
        font-size: 30px;
    }
    .white {
        background-color: white;
        &:focus {
            background-color: rgb(158, 217, 235);
        }
    }
    .black {
        background-color: black;
        &:focus {
            background-color: rgb(80, 107, 116);
        }
    }
</style>

// react-src/src/components/Grid/Grid.tsx
import { useRef, useState, useCallback } from 'react';
import { useCrossword } from '../../state/CrosswordContext';
import './Grid.css';

const SIZES = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15];

export default function Grid() {
  const { state, dispatch } = useCrossword();
  const { grid } = state;
  const size = grid.length;

  const [hideLetters, setHideLetters] = useState(false);
  const [currentRow, setCurrentRow] = useState<number | null>(null);
  const [currentCol, setCurrentCol] = useState<number | null>(null);

  // 2D array of refs to TD elements for programmatic focus
  const cellRefs = useRef<(HTMLTableCellElement | null)[][]>([]);

  // Ensure cellRefs has the right dimensions
  if (cellRefs.current.length !== size) {
    cellRefs.current = Array.from({ length: size }, () => Array(size).fill(null));
  }

  function focusCell(row: number, col: number) {
    const bounded_row = Math.max(0, Math.min(size - 1, row));
    const bounded_col = Math.max(0, Math.min(size - 1, col));
    setCurrentRow(bounded_row);
    setCurrentCol(bounded_col);
    cellRefs.current[bounded_row]?.[bounded_col]?.focus();
  }

  function handleFocus(row: number, col: number) {
    setCurrentRow(row);
    setCurrentCol(col);
  }

  const handleKeyDown = useCallback(
    (row: number, col: number, event: React.KeyboardEvent<HTMLTableCellElement>) => {
      if (event.metaKey || event.ctrlKey) return;
      event.preventDefault();

      switch (event.key) {
        case ' ':
          dispatch({ type: 'TOGGLE_CELL', row, col });
          break;
        case 'Backspace':
        case 'Delete':
          dispatch({ type: 'SET_CELL_LETTER', row, col, letter: '' });
          break;
        case 'ArrowUp':
          focusCell((currentRow ?? row) - 1, currentCol ?? col);
          break;
        case 'ArrowDown':
          focusCell((currentRow ?? row) + 1, currentCol ?? col);
          break;
        case 'ArrowLeft':
          focusCell(currentRow ?? row, (currentCol ?? col) - 1);
          break;
        case 'ArrowRight':
          focusCell(currentRow ?? row, (currentCol ?? col) + 1);
          break;
        default:
          if (/^[a-z]$/i.test(event.key)) {
            dispatch({
              type: 'SET_CELL_LETTER',
              row,
              col,
              letter: event.key.toUpperCase(),
            });
          }
      }
    },
    [currentRow, currentCol, dispatch, size]
  );

  function handleSizeChange(event: React.ChangeEvent<HTMLSelectElement>) {
    const newSize = parseInt(event.target.value);
    dispatch({ type: 'SET_SIZE', size: newSize });
  }

  return (
    <div>
      <p className="grid-settings dont-print">
        <span className="grid-setting">
          Size:{' '}
          <select value={size} onChange={handleSizeChange}>
            {SIZES.map(s => (
              <option key={s} value={s}>
                {s}
              </option>
            ))}
          </select>
        </span>
        <span className="grid-setting">
          Hide answers:{' '}
          <input
            type="checkbox"
            checked={hideLetters}
            onChange={e => setHideLetters(e.target.checked)}
          />
        </span>
      </p>

      <table className="grid-table">
        <tbody>
          {grid.map((row, rowIndex) => (
            <tr key={rowIndex}>
              {row.map((cell, colIndex) => (
                <td
                  key={colIndex}
                  tabIndex={0}
                  className={`cell ${cell.isWhite ? 'cell-white' : 'cell-black'}`}
                  onFocus={() => handleFocus(rowIndex, colIndex)}
                  onKeyDown={e => handleKeyDown(rowIndex, colIndex, e)}
                  ref={el => {
                    if (!cellRefs.current[rowIndex]) {
                      cellRefs.current[rowIndex] = Array(size).fill(null);
                    }
                    cellRefs.current[rowIndex][colIndex] = el;
                  }}
                >
                  {cell.isWhite && (
                    <div className="cell-layout">
                      <div className="cell-number">{cell.cellNumber ?? ''}</div>
                      {!hideLetters && (
                        <div className="cell-letter">{cell.letter}</div>
                      )}
                    </div>
                  )}
                </td>
              ))}
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}
